Pull from developing branch to main branch
gruvix/Simon-Dice pull request #3
Opened 2023-10-12 22:41 UTC by gruvix

![imagen](https://github.com/gruvix/Simon-Dice/assets/72170232/cf7587ca-ee88-400a-badb-0e5fd2691137)

2023-10-12 23:34 UTC, fsodano requested changes

2023-10-12 23:34 UTC, fsodano commented on css/main.css
> +#turn{
ojo con el spanglish, tenés cuadro y turn, player, etc.

2023-10-12 23:34 UTC, fsodano commented on index.html
> +            &nbsp;Ronda N#<a id="ronda">-</a>
esto por qué es un anchor si no es clickeable? Hacelo un <span> en todo caso

2023-10-12 23:34 UTC, fsodano commented on index.html
> +            <!-- Third square -->
suman estos comentarios? se llama id="cuadro3", no podés ser mucho más explícito que eso

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +    tic = document.querySelector("#speed").value;
mmm esta variable global no se si me gusta, mejor preguntarla en la función que la use

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +let tic = 1000; //controls general game speed, in miliseconds
entonces ponele `const gameSpeedInMs` y ahorrate el comentario

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +/////////////////////////////////////////////////////ROUND HANDLER////////////////////////////////////////
si sentís que debés dividir el archivo en secciones entonces ponelo en otro archivo y ahorrate el comentario

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +        const time = (index+0.5) * tic;
0.5? magic number

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +        setTimeout(handleSound, time+(0.5*tic), colorBox);
este 0.5 asumo que está relacionado al anterior, eso tiene que ir en otro lado con un nombre explícito

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +    return `cuadro${Math.floor(Math.random() * 4) + 1}`;
el 4 qué es? Y si mañana quiero 5 colores qué pasa?

2023-10-12 23:34 UTC, fsodano commented on js/main.js
> +function reduceCounterBy100Ms(ultimoValor){
creo que nunca llamás a esta función

2023-10-13 20:02 UTC, gruvix commented on index.html
> +            &nbsp;Ronda N#<a id="ronda">-</a>
Html es lo que menos manejo
no se que sería un "un" (o quizá solo falta especificar) 
me revisé la lista entera de elementos de html y no encontré uno que sirviera específicamente para esto, ¿hay algún elemento que se use para estas situaciones que no aplique ningún estilo?

2023-10-13 20:12 UTC, gruvix commented on js/main.js
> +function reduceCounterBy100Ms(ultimoValor){
es llamada desde la funcion startSequence

2023-10-13 20:59 UTC, gruvix commented on js/main.js
> +        setTimeout(handleSound, time+(0.5*tic), colorBox);
era para compensar una diferencia de tiempo entre la animación y el sonido pero terminé haciendo que tuviera otros problemas en velocidad lenta

2023-10-13 21:00 UTC, closed without merging